services:
  db:
    image: postgres:16-alpine
    restart: always
    networks:
      - ocd_net
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workout_db
    # You no longer even NEED to expose 5432 to your host 
    # since pgAdmin will talk to it over the internal Docker network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - ocd_net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80" # Access it at http://localhost:8080
    depends_on:
      - db

networks:
  ocd_net:
    driver: bridge
    external: true

volumes:
  db-data:
